# --- 基础卡 ---

[MASO_STRIKE]
title = "打击"
description = "造成{Damage:diff()}点伤害。"

[MASO_DEFEND]
title = "防御"
description = "获得{Block:diff()}点[gold]格挡[/gold]。"

# --- 攻击卡 (Attack) ---

[WHIP_OF_PENANCE]
title = "忏悔之鞭"
description = "造成{Damage:diff()}点伤害。失去{HpLoss:diff()}点生命。"

[BLOOD_RECKONING]
title = "鲜血结算"
description = "{IfUpgraded:show:[gold]固有[/gold]。|}造成{Damage:diff()}点伤害。每当你由于卡牌效果失去生命值，此伤害增加{Extra:diff()}点。"

[SADISTIC_Glee]
title = "施虐狂欢"
description = "造成{Damage:diff()}点伤害{Repeat:diff()}次。每下一次攻击都会使你失去1点生命。"

# --- 技能卡 (Skill) ---

[EMBRACE_PAIN]
title = "拥抱痛苦"
description = """
获得{Block:diff()}点[gold]格挡[/gold]。
如果你当前的生命值低于50%，获得{Strength:diff()}点[gold]力量[/gold]。
"""

[SACRIFICIAL_RITE]
title = "牺牲仪式"
description = "抽{Cards:diff()}张牌。将{Shivs:diff()}张[gold]鲜血之刃[/gold]放入你的[gold]手牌[/gold]。"

# --- 能力卡 (Power) ---

[STIGMATA]
title = "圣痕"
description = "在你的回合开始时，失去1点生命并获得{Vigor:diff()}点[gold]活力[/gold]。"

[PAIN_RELIANCE]
title = "苦痛依赖"
description = "每当你失去生命值时，获得{Block:diff()}点[gold]格挡[/gold]。"

# --- 衍生卡/特殊状态 ---

[BLOOD_BLADE]
title = "鲜血之刃"
description = "{IfUpgraded:show:[gold]保留[/gold]。|}造成{Damage:diff()}点伤害。\n[gold]消耗[/gold]。"