[DefendLupa]
title = "防御"
description = "获得{Block:diff()}点[gold]格挡[/gold]。"

[DefendMaso]
title = "防御"
description = "获得{Block:diff()}点[gold]格挡[/gold]。"

[StrikeMaso]
title = "打击"
description = "造成{Damage:diff()}点伤害。"

[StrikeLupa]
title = "打击"
description = "造成{Damage:diff()}点伤害。"
