[DefendLupa]
title = "邀请"
description = "获得{Block:diff()}点[gold]格挡[/gold]。"
flavor = "这里面请。"
sfw.title = "防御"
sfw.flavor = ""

[DefendMaso]
title = "邀请"
description = "获得{Block:diff()}点[gold]格挡[/gold]。"
flavor = "这里面请。"
sfw.title = "防御"
sfw.flavor = ""

[StrikeLupa]
title = "亲吻"
description = "造成{Damage:diff()}点伤害。"
flavor = "（づ￣3￣）づ╭❤～"
sfw.title = "打击"
sfw.flavor = ""

[StrikeMaso]
title = "亲吻"
description = "造成{Damage:diff()}点伤害。"
flavor = "（づ￣3￣）づ╭❤～"
sfw.title = "打击"
sfw.flavor = ""

