# ============================================================================
# Mod 配置界面
# ============================================================================

[ContentFilter]
title = "内容过滤"

[EnableSafeForWork]
title = "启用和谐模式"
hover.desc = """
开启后，所有可能引起不适的内容将被和谐处理。
（现在开/关后好像不需要重启？我不太清楚塔二的代码是怎么运作的。）
"""

[EnableGuro]
title = "启用猎奇内容"
hover.desc = """
必须关闭和谐模式才能起效。
选择此选项表明你已接受你会遭遇大量猎奇内容的事实，
其包括血腥、暴力、排泄物或其他可能引起不适的内容。
（现在开/关后好像不需要重启？我不太清楚塔二的代码是怎么运作的。）
"""

[Performance]
title = "性能"

[EnablePerformanceMode]
title = "启用性能模式"
hover.desc = """
开启性能模式后，部分特效表现可能会被减弱。
（目前没有用。）
"""

[RefreshLocalization]
title = "刷新本地化资源"
hover.desc = "点击刷新本地化资源（部分可能需要重启）"

# ============================================================================
# 猎奇内容警告
# ============================================================================

[GuroText]
cannotStart = "无法开始游戏"
warningMessage = """
你可以在打开 #g和谐模式 的情况下游玩具有 #r猎奇内容 的角色，或是在关闭 #g和谐模式 并且启用 #r猎奇内容 的情况下游玩。
NL 请自行前往主菜单的mod设置选项卡进行设置。
"""