# ============================================================================
# Mod 配置界面
# ============================================================================

[ContentFilter]
title = "内容过滤"

[EnableNotSafeForWork]
title = "允许工作场所不适宜内容"
hover.desc = """
开启后，你可以进一步细分允许显示的内容。
若关闭，本模组将强制使用和谐版本的文本与图片。
（现在开/关后好像不需要重启？我不太清楚塔二的代码是怎么运作的。）
"""

[ShowNsfwImages]
title = "显示NSFW内容图片"
hover.desc = """
仅在“允许工作场所不适宜内容”时可选。
决定是否在游戏中使用不适合公共场合的视觉素材。
若关闭，相关图片将由和谐版占位图替代。
"""

[EnableGuroContent]
title = "允许猎奇内容"
hover.desc = """
仅在“允许工作场所不适宜内容”时可选。
[red]选择此选项表明你已接受你会遭遇大量猎奇内容的事实，
其包括血腥、暴力、排泄物或其他可能引起不适的内容。[/red]
"""

[ShowGuroImages]
title = "显示猎奇/血腥图片"
hover.desc = """
仅在“允许猎奇内容”时可选。
决定是否显示猎奇/血腥相关的视觉素材。
若关闭，相关内容将由常规 NSFW 或和谐版图片替代。
"""

[Performance]
title = "性能"

[EnablePerformanceMode]
title = "启用性能模式"
hover.desc = """
开启性能模式后，部分特效表现可能会被减弱。
（目前没有用。）
"""

# ============================================================================
# 猎奇内容警告
# ============================================================================

[GuroText]
cannotStart = "无法开始游戏"
warningMessage = """
你可以在打开 #g和谐模式 的情况下游玩具有 #r猎奇内容 的角色，或是在关闭 #g和谐模式 并且启用 #r猎奇内容 的情况下游玩。
NL 请自行前往主菜单的mod设置选项卡进行设置。
"""