[MASO_START_RELIC]
description = """
[gold]初始遗物[/gold]。
每消耗1点能量，获得2点[gold]快感[/gold]。
每累计获得10点[gold]快感[/gold]，使本回合内下一张牌的费用减少1点。
受到伤害时，将伤害量转化为等量[gold]腐朽[/gold]层数，回合结束时受到等同于[gold]腐朽[/gold]层数的伤害。
"""
flavor = "在苦痛中，她找到了力量的真谛。"
title = "苦行印记"