// <auto-generated /> 告诉其他代码分析工具不要检查这个生成的文件
#nullable enable
using System;
using System.Diagnostics;

namespace Superstitio.Analyzer;

/// <summary>
/// 约束一个接口只能被指定的类型实现。
/// 将此特性应用于接口，并传入允许实现该接口的目标类型。
/// 分析器会在编译时检查违反此约束的情况。
/// </summary>
/// <remarks>
/// 可多次应用以允许多个类型实现同一个接口。
/// </remarks>
[Conditional("SUPERSTITIO_ANALYZER_D8D5477E")] 
[AttributeUsage(AttributeTargets.Interface, AllowMultiple = true)]
internal sealed class AttachedToAttribute(Type targetType) : Attribute
{
    /// <summary>
    /// 目标类型
    /// </summary>
    public Type TargetType { get; } = targetType;
}